name: deploy
on:
  push:
    branches:    
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v1.0.3
      with:
        host: mbkv.io
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
